# Generated by Django 5.0.2 on 2024-03-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_new_product', models.ImageField(upload_to='icons_new_products', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение новостного продукта',
                'verbose_name_plural': 'Изображения новостного продукта',
            },
        ),
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'verbose_name': 'Изображение слайдера', 'verbose_name_plural': 'Изображения слайдеров'},
        ),
    ]
