# Generated by Django 5.0.2 on 2024-03-06 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(editable=False, max_length=128, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Характеристика продукта',
                'verbose_name_plural': 'Характеристики продуктов',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(editable=False, max_length=128, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('name_eng', models.CharField(max_length=128, verbose_name='Наименование (англ.)')),
                ('slug', models.SlugField(editable=False, max_length=128, unique=True, verbose_name='Слаг')),
                ('icon_image', models.ImageField(upload_to='icons_products', verbose_name='Изображение продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена (руб.)')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка (%)')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Количество в наличии')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.source', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Базовый продукт',
                'verbose_name_plural': 'Базовые продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_string', models.CharField(blank=True, help_text='Значение задается текстом (Автор, обложка, Цвет)', max_length=250, null=True, verbose_name='Текстовое значение характеристики')),
                ('value_integer', models.IntegerField(blank=True, help_text='Значение задается целым числом (Вес книги, год выпуска)', null=True, verbose_name='Числовое значение характеристики')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Продукт')),
                ('value_genres', models.ManyToManyField(blank=True, help_text='Поле для категорий, где есть жанры (Манга, манхва. маньхуа, ранобэ)', null=True, to='catalog.genre', verbose_name='Жанры')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.property', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Сопоставление характеристик продуктов',
                'verbose_name_plural': 'Сопоставление характеристик продуктов',
            },
        ),
    ]
